In [2]:
import tensorflow as tf

In [8]:
x = tf.constant([3.0])    #scalar

In [9]:
vector = tf.range(4)    #vector
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>

In [7]:
matrix = tf.reshape(tf.range(20),(5,4)) #reshape takes 3 parameters number of elements,rows,columns
matrix

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])>

In [10]:
tf.transpose(matrix)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])>

In [12]:
tensor = tf.reshape(tf.range(24),(2,3,4)) #tensor
tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

### Norm

In [14]:
vector = tf.constant([3.0,-4.0])
L1 = tf.reduce_sum(tf.abs(vector)) #L1 norm is sum of absolute values of a vector elements i.e., scalars
L1

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [15]:
L2 = tf.norm(vector)   #L2 norm is square root of sum of squares of the vector elements Euclidean distance
L2

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [16]:
Frobenius_norm = tf.norm(tf.ones((4,9))) #square root of the sum of the squares of the matrix elements
Frobenius_norm

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>